import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Aravind Jaimon | Lead Software Engineer",
    short_name: "Aravind Jaimon",
    description:
      "Portfolio of Aravind Jaimon - Lead Software Engineer building systems for millions",
    start_url: "/",
    display: "standalone",
    background_color: "#0A0A0A",
    theme_color: "#0A0A0A",
    // Generated by app/apple-icon.tsx — the only PNG icon the site ships
    icons: [{ src: "/apple-icon", sizes: "180x180", type: "image/png" }],
  };
}
